### ISSUE TITLE
UZG01 stopped working until Zigbee module restart

### ISSUE THREAD

**Issue by hilsonp** [xyzroe/ZigStarGW-FW#27]
Hello,

I bought the Zigstar UZG01 to stabilize my zigbee network.
So far, things are better but not perfect yet as I had a few hic-hups.
Since my automation rely on some zigbee device, I want to tend to zero fault which is why I will spend time reporting problems in the hope to improve the product hence my network stability.

All of a sudden my zigbee network stopped working.
I checked the Z2M logs and all lines going on error at one point in time (2024-03-22 15:03:06).
```
info  2024-03-22 15:02:01: MQTT publish: topic 'zigbee2mqtt/Oven', payload '{"child_lock":"UNLOCK","current":0,"energy":187.96,"indicator_mode":"off/on","last_seen":"2024-03-22T14:02:01.824Z","linkquality":51,"power":0,"power_outage_memory":"on","state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":
238}'
info  2024-03-22 15:02:02: MQTT publish: topic 'zigbee2mqtt/Kitchen Boiler', payload '{"child_lock":"UNLOCK","current":0,"energy":411.24,"indicator_mode":"off/on","last_seen":"2024-03-22T14:02:02.241Z","linkquality":98,"power":0,"power_outage_memory":"on","state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,
"voltage":238}'
error 2024-03-22 15:03:06: Publish 'set' 'state' to 'always_on_plugs' failed: 'Error: Command 1 genOnOff.on({}) failed (SRSP - AF - dataRequestExt after 6000ms)'
error 2024-03-22 15:03:40: Publish 'set' 'brightness' to 'Office Lamp' failed: 'Error: Command 0x0c4314fffeede29d/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactio
nSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
error 2024-03-22 15:03:46: Publish 'set' 'brightness' to 'Office Lamp Desk 1' failed: 'Error: Command 0x84b4dbfffef8c619/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"tra
nsactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
error 2024-03-22 15:03:52: Publish 'set' 'color_temp' to 'Office Lamp' failed: 'Error: Command 0x0c4314fffeede29d/1 lightingColorCtrl.moveToColorTemp({"colortemp":250,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transa
ctionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'

```

I first restarted Z2M but it failed to attach to the UZG:
```
info  2024-03-22 17:53:46: Logging to console and directory: '/config/zigbee2mqtt/log/' filename: zigbee_2024-03-22.17-53-46.log
info  2024-03-22 17:53:46: Starting Zigbee2MQTT version 1.36.0 (commit #unknown)
info  2024-03-22 17:53:46: Starting zigbee-herdsman (0.35.1)
error 2024-03-22 17:54:06: Error while starting zigbee-herdsman
error 2024-03-22 17:54:06: Failed to start zigbee
error 2024-03-22 17:54:06: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-03-22 17:54:06: Exiting...
error 2024-03-22 17:54:07: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```

I then connected to the UZG web interface.
All seemed fine (pages where refreshing correctly).

I went to "System and Tools" then "System Control" and clicked "Zigbee Restart".
I then restarted Z2M and all went fine.

The UZG01 uptime was around 7d on Ethernet.

The Device information is:
Model:	UZG-01
ESP32 Firmware ver:	0.1.5 (2023-09-06 12:01:02.723464)
ESP32 version:	ESP32-D0WDQ6
ESP32 temperature:	47.00 °C
ESP32 frequency:	2 cores @ 240 MHz
ESP32 flash size:	4 Mb, external
ESP32 Free heap:	189 / 289 KiB
CC2652P version:	CC2652PP1FRGZR
CC2652P flash size:	352 Kb

I believe I should upgrade the UZG01.

If you have no idea what could have gone wrong, what information can I provide next time before taking actions ?
Should I have taken a look at the "System and Tools" / "System Tools" / "Debug console" ?

Thank you in advance,

Pierre

**Comment by xyzroe** [comment]
Hi. 
First - UZG don't use this firmware. You should look for https://github.com/mercenaruss/uzg-firmware
Second - your problem is related to Zigbee chip, chat has its own firmware. https://github.com/mercenaruss/uzg-firmware/issues/22

**Comment by xyzroe** [comment]
Some more info about Zigbee firmware https://github.com/Koenkk/Z-Stack-firmware/discussions/496

**Comment by hilsonp** [comment]
Ok. Sorry for disturbing... I'll follow-up in the other repo.
